[versions]
sdk-compile = "33"
sdk-min = "21"
sdk-target = "33"

compose-bom = "2023.06.00"
compose-compiler = "1.4.7"
accompanist = "0.30.1"
activity-compose = "1.7.2"
constraint-compose = "1.0.1"

plugin-android-gradle = "8.1.0"
plugin-kotlin = "1.8.21"
plugin-detekt = "1.21.0"
plugin-spotless = "6.5.1"
plugin-mavenpublish = "0.21.0"

java-jvmTarget = "1.8"
java-sourceCompatibility = "1.8"
java-targetCompatibility = "1.8"
core-ktx = "1.9.0"
junit = "4.13.2"
androidx-test-ext-junit = "1.1.5"
espresso-core = "3.5.1"
appcompat = "1.6.1"
material = "1.8.0"

[libraries]
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
compose-foundation = { module = "androidx.compose.foundation:foundation" }
compose-material3 = { module = "androidx.compose.material3:material3" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-uitooling = { module = "androidx.compose.ui:ui-tooling" }
compose-uitoolingpreview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-activitycompose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "constraint-compose" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

[plugins]
android-application = { id = "com.android.application", version.ref = "plugin-android-gradle" }
android-library = { id = "com.android.library", version.ref = "plugin-android-gradle" }
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "plugin-kotlin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "plugin-detekt" }
spotless = { id = "com.diffplug.spotless", version.ref = "plugin-spotless" }
mavenpublish = { id = "com.vanniktech.maven.publish", version.ref = "plugin-mavenpublish" }
